### ISSUE TITLE
Fails to compile with mingw-64 (GCC 8.1.0) on Windows 10

### ISSUE THREAD

**Issue by SpectralCascade** [samhocevar/portable-file-dialogs#45]
Hiya, I came across an issue while attempting to build the single-header as part of a Code::Blocks project (using mingw-64 on Windows 10). Specifically, I get a few of these errors when including the header in a .cpp source file:

`portable-file-dialogs.h:1245:13: error: invalid use of incomplete type 'IFileDialog' {aka 'struct IFileDialog'}`

**Comment by DJLink** [comment]
IFileDialog is part of <ShObjldl.h>, found a similar issue with someone trying to use mingw-64 with IFileDialog,
doesn't seem to be an answer but I wonder if this is really an issue with mingw-64 or if it needs a different header for this case?
http://mingw.5.n7.nabble.com/Issues-with-IFileDialog-td35029.html
