### ISSUE TITLE
error building on VS2015 

### ISSUE THREAD

**Issue by DJLink** [samhocevar/portable-file-dialogs#14]
Hi,

I've been using portable-file-dialogs, but with the update https://github.com/samhocevar/portable-file-dialogs/commit/5d96dae879e4f155c75abc6c22cea1f019e1d651 for folder selection it stopped building.

```
portable-file-dialogs.h(501): error C2065: 'callback': undeclared identifier
``` 

I took a look at the code and can't figure out a good way to fix it, seems to be that because callback is not within that lambda scope it can't resolve, but it's not possible to pass [&] as it stops being a valid BFFCallback?

![image](https://user-images.githubusercontent.com/423769/59916908-61a77080-9418-11e9-94d3-c160a611592f.png)

I don't mind fixing this myself just wanted to know an idea of the best way to do so. Also lp and pData variables in callback will throw an unreferenced formal parameter as they are not being used.

Thank you for your time.

**Comment by samhocevar** [comment]
Thanks for reporting this. It is a [bug in the Visual Studio compiler](https://developercommunity.visualstudio.com/content/problem/1993/decltype-in-capture-less-lambdas-should-see-extern.html) which unfortunately was only fixed in versions 2017 and later, as you can see. I’m happy to try to keep the code VS2015-friendly, though.

Your analysis is correct, there’s a catch-22 here that will prevent fixing this in an elegant way. I’ll think about it but if you have a suggestion let me know.

**Comment by wesleyluohao** [comment]
This problem can be solved by changing the callback function and the variable wdefault _ path, wtitle to the global.
![image](https://user-images.githubusercontent.com/14138895/62766577-5b9f4900-bac5-11e9-83c9-c8ae01922b9f.png)

**Comment by DJLink** [comment]
Thanks. Personally I've since updated from VS2015 to 2017 so I don't need the fix anymore. This is still useful for anyone who's still on VS2015

**Comment by funbiscuit** [comment]
Was fixed by PR #19 
Can close this issue
